### ISSUE TITLE
小哥哥 看了您写的NLP代码很厉害 有个问题想要和您探讨一下。怎么可以联系到您呢？

### ISSUE THREAD

**Issue by yofo** [chansonzhang/FirstNLP#2]

**Comment by albert-leiming-du** [comment]
想联系小哥哥直接就给他打电话啊。。。。如果你是妹子的话。。。

**Comment by yofo** [comment]
好啊好啊，你有电话吗

**Comment by albert-leiming-du** [comment]
有，但是不能告诉你。。。。。
直接给他发邮件啊，github上应该有邮箱的。。。。
这哥们在写代码，估计git上的issue暂时回不了。。

**Comment by yofo** [comment]
他要是肯翻邮箱的话，我大概不必跑过来“探讨”这除了英文单词，完全看不懂的NLP了
不过。。。你知道他现在单身吗？
如果不是，那你就假装我不存在。
如果是，你帮我提醒他，写完代码要记得看看邮箱啊。。。
还有。。。谢谢你~

**Comment by albert-leiming-du** [comment]
。。。。。。。。
他不是单身。。。。
所以你不认识这个小哥哥吗？墙角有还是可以挖的， 我告诉他先。。。。。

**Comment by yofo** [comment]
不要告诉，我消失了

**Comment by albert-leiming-du** [comment]
妹子别走。。。。我也是单身。。。。
